ada_feeding_action_servers:
  ros__parameters:
    default:
      AcquireFood:
        action_type: ada_feeding_msgs.action.AcquireFood
        tick_rate: 10
        tree_class: ada_feeding.trees.AcquireFoodTree
        tree_kwargs:
          max_velocity_scaling_move_above: 1.0
          max_velocity_scaling_move_into: 1.0
          max_velocity_scaling_to_resting_configuration: 1.0
          allowed_planning_time_for_move_above: 4.5 # secs, was 0.5 default; real octomap collision checking needs more time
          allowed_planning_time_for_move_into: 4.5 # secs, was 0.5 default; real octomap collision checking needs more time
          resting_joint_positions:
          - -2.02859619
          - 0.7262315018
          - -0.03089232776
          - -1.933999344
          - 0.02722713633
          - -1.161865683
          - 1.592612942
        tree_kws:
        - resting_joint_positions
        - max_velocity_scaling_move_above
        - max_velocity_scaling_move_into
        - max_velocity_scaling_to_resting_configuration
        - allowed_planning_time_for_move_above
        - allowed_planning_time_for_move_into
      ActivateController:
        action_type: ada_feeding_msgs.action.ActivateController
        tick_rate: 10
        tree_class: ada_feeding.trees.ActivateControllerTree
      MoveAbovePlate:
        action_type: ada_feeding_msgs.action.MoveTo
        tick_rate: 10
        tree_class: ada_feeding.trees.MoveToConfigurationWithFTThresholdsTree
        tree_kwargs:
          f_mag: 4.0
          joint_positions:
          - 0.07400196
          - 0.4459316
          - 3.136531
          - 4.759338
          - 6.251071
          - 5.133537
          - 1.541824
          max_velocity_scaling_factor: 1.0
          toggle_watchdog_listener: false
        tree_kws:
        - joint_positions
        - toggle_watchdog_listener
        - f_mag
        - max_velocity_scaling_factor
      MoveFromMouth:
        action_type: ada_feeding_msgs.action.MoveTo
        tick_rate: 10
        tree_class: ada_feeding.trees.MoveFromMouthTree
        tree_kwargs:
          cartesian_jump_threshold_to_staging_configuration: 2.0
          cartesian_max_step_to_staging_configuration: 0.01
          linear_speed_near_mouth: 0.08
          max_linear_speed_to_staging_configuration: 0.15
          max_velocity_scaling_factor_to_end_configuration: 1.0
          max_velocity_scaling_factor_to_staging_configuration: 0.6
          staging_configuration_position:
          - 0.28323
          - 0.07289
          - 0.69509
          staging_configuration_quat_xyzw:
          - 0.00472
          - 0.69757
          - 0.71645
          - -0.00811
        tree_kws:
        - staging_configuration_position
        - staging_configuration_quat_xyzw
        - max_linear_speed_to_staging_configuration
        - linear_speed_near_mouth
        - max_velocity_scaling_factor_to_staging_configuration
        - max_velocity_scaling_factor_to_end_configuration
        - cartesian_jump_threshold_to_staging_configuration
        - cartesian_max_step_to_staging_configuration
      MoveToConfiguration:
        action_type: ada_feeding_msgs.action.MoveToConfiguration
        tick_rate: 10
        tree_class: ada_feeding.trees.MoveToConfigurationWithFTThresholdsTree
        tree_kwargs:
          f_mag: 4.0
          max_velocity_scaling_factor: 1.0
          toggle_watchdog_listener: false
        tree_kws:
        - toggle_watchdog_listener
        - f_mag
        - max_velocity_scaling_factor
      MoveToMouth:
        action_type: ada_feeding_msgs.action.MoveToMouth
        tick_rate: 10
        tree_class: ada_feeding.trees.MoveToMouthTree
        tree_kwargs:
          face_detection_msg_timeout: 10.0
          face_detection_timeout: 5.0
          fork_target_orientation_from_mouth:
          - 0.5
          - -0.5
          - -0.5
          - 0.5
          linear_speed_near_mouth: 0.06
          max_linear_speed: 0.15
          plan_distance_from_mouth:
          - 0.025
          - 0.0
          - -0.01
        tree_kws:
        - face_detection_msg_timeout
        - face_detection_timeout
        - fork_target_orientation_from_mouth
        - plan_distance_from_mouth
        - max_linear_speed
        - linear_speed_near_mouth
      MoveToRestingPosition:
        action_type: ada_feeding_msgs.action.MoveTo
        tick_rate: 10
        tree_class: ada_feeding.trees.MoveToConfigurationWithWheelchairWallTree
        tree_kwargs:
          allowed_planning_time: 1.0
          goal_configuration:
          - -1.42859619
          - 0.7262315018
          - -0.03089232776
          - -1.933999344
          - 0.02722713633
          - -1.161865683
          - 1.592612942
          max_velocity_scaling_factor: 1.0
          orientation_constraint_quaternion:
          - 0.707168
          - 0.0
          - 0.0
          - 0.707168
          orientation_constraint_tolerances:
          - 0.6
          - 3.14159
          - 0.5
        tree_kws:
        - goal_configuration
        - allowed_planning_time
        - max_velocity_scaling_factor
      MoveToStagingConfiguration:
        action_type: ada_feeding_msgs.action.MoveTo
        tick_rate: 10
        tree_class: ada_feeding.trees.MoveToConfigurationWithWheelchairWallTree
        tree_kwargs:
          allowed_planning_time: 1.0
          goal_configuration:
          - -2.152514566
          - -1.012290966
          - -0.03106686069
          - -1.034980246
          - 2.162113877
          - -1.44809968
          - 1.58947135
          max_velocity_scaling_factor: 1.0
          orientation_constraint_quaternion:
          - 0.707168
          - 0.0
          - 0.0
          - 0.707168
          orientation_constraint_tolerances:
          - 0.6
          - 3.14159
          - 0.5
        tree_kws:
        - goal_configuration
        - allowed_planning_time
        - max_velocity_scaling_factor
      MoveToStowLocation:
        action_type: ada_feeding_msgs.action.MoveTo
        tick_rate: 10
        tree_class: ada_feeding.trees.MoveToConfigurationWithFTThresholdsTree
        tree_kwargs:
          f_mag: 4.0
          joint_positions:
          - -1.42859619
          - 0.6515314098
          - -0.03089232776
          - -2.402620248
          - -0.02722713633
          - -0.6394886379
          - 1.592612942
          max_velocity_scaling_factor: 1.0
          toggle_watchdog_listener: false
        tree_kws:
        - joint_positions
        - toggle_watchdog_listener
        - f_mag
        - max_velocity_scaling_factor
      StartServo:
        action_type: ada_feeding_msgs.action.Trigger
        tick_rate: 10
        tree_class: ada_feeding.trees.StartServoTree
      StopServo:
        action_type: ada_feeding_msgs.action.Trigger
        tick_rate: 10
        tree_class: ada_feeding.trees.StopServoTree
      TestMoveToPose:
        action_type: ada_feeding_msgs.action.MoveTo
        tick_rate: 10
        tree_class: ada_feeding.trees.MoveToPoseTree
        tree_kwargs:
          max_velocity_scaling_factor: 1.0
          position:
          - 0.28323
          - 0.07289
          - 0.69509
          quat_xyzw:
          - 0.00472
          - 0.69757
          - 0.71645
          - -0.00811
        tree_kws:
        - position
        - quat_xyzw
        - max_velocity_scaling_factor
      planning_scene_namespace_to_use: seated
      server_names:
      - MoveAbovePlate
      - AcquireFood
      - MoveToRestingPosition
      - MoveToStagingConfiguration
      - MoveToMouth
      - MoveFromMouth
      - MoveToStowLocation
      - TestMoveToPose
      - StartServo
      - StopServo
      - ActivateController
      - MoveToConfiguration
    watchdog_timeout_sec: 0.5
