ada_feeding_action_servers:
  ros__parameters:
    default:
      AcquireFood:
        action_type: ada_feeding_msgs.action.AcquireFood
        tick_rate: 10
        tree_class: ada_feeding.trees.AcquireFoodTree
        tree_kwargs:
          joint_positions:
          - 3.7584342379702265
          - -3.0680026297628116
          - 0.11208646011532394
          - 0.00303070749096387
          - -0.05027405112606054
          - -1.7464533479809023
          - -2.085948872615267
          max_velocity_scaling_move_above: 1.0
          max_velocity_scaling_move_into: 1.0
          max_velocity_scaling_to_resting_configuration: 1.0
          resting_joint_positions:
          - -1.94672
          - 2.51268
          - 0.35653
          - -4.76501
          - 5.99991
          - 4.99555
        tree_kws:
        - resting_joint_positions
        - max_velocity_scaling_move_above
        - max_velocity_scaling_move_into
        - max_velocity_scaling_to_resting_configuration
      ActivateController:
        action_type: ada_feeding_msgs.action.ActivateController
        tick_rate: 10
        tree_class: ada_feeding.trees.ActivateControllerTree
      MoveAbovePlate:
        action_type: ada_feeding_msgs.action.MoveTo
        tick_rate: 10
        tree_class: ada_feeding.trees.MoveToConfigurationWithFTThresholdsTree
        tree_kwargs:
          f_mag: 4.0
          joint_positions:
          - -0.38154221176943864
          - -2.6442809484504473
          - 1.1181369283438862
          - 0.024664264415837685
          - 2.1480679053200373
          - -1.3870637228141465
          - -1.071020326898642
          max_velocity_scaling_factor: 1.0
          toggle_watchdog_listener: false
        tree_kws:
        - joint_positions
        - toggle_watchdog_listener
        - f_mag
        - max_velocity_scaling_factor
      MoveFromMouth:
        action_type: ada_feeding_msgs.action.MoveTo
        tick_rate: 10
        tree_class: ada_feeding.trees.MoveFromMouthTree
        tree_kwargs:
          cartesian_jump_threshold_to_staging_configuration: 2.0
          cartesian_max_step_to_staging_configuration: 0.01
          linear_speed_near_mouth: 0.08
          max_linear_speed_to_staging_configuration: 0.15
          max_velocity_scaling_factor_to_end_configuration: 1.0
          max_velocity_scaling_factor_to_staging_configuration: 0.6
          staging_configuration_position:
          - 0.28323
          - 0.07289
          - 0.69509
          staging_configuration_quat_xyzw:
          - 0.00472
          - 0.69757
          - 0.71645
          - -0.00811
        tree_kws:
        - staging_configuration_position
        - staging_configuration_quat_xyzw
        - max_linear_speed_to_staging_configuration
        - linear_speed_near_mouth
        - max_velocity_scaling_factor_to_staging_configuration
        - max_velocity_scaling_factor_to_end_configuration
        - cartesian_jump_threshold_to_staging_configuration
        - cartesian_max_step_to_staging_configuration
      MoveToConfiguration:
        action_type: ada_feeding_msgs.action.MoveToConfiguration
        tick_rate: 10
        tree_class: ada_feeding.trees.MoveToConfigurationWithFTThresholdsTree
        tree_kwargs:
          f_mag: 4.0
          max_velocity_scaling_factor: 1.0
          toggle_watchdog_listener: false
        tree_kws:
        - toggle_watchdog_listener
        - f_mag
        - max_velocity_scaling_factor
      MoveToMouth:
        action_type: ada_feeding_msgs.action.MoveToMouth
        tick_rate: 10
        tree_class: ada_feeding.trees.MoveToMouthTree
        tree_kwargs:
          face_detection_msg_timeout: 10.0
          face_detection_timeout: 5.0
          fork_target_orientation_from_mouth:
          - 0.5
          - -0.5
          - -0.5
          - 0.5
          linear_speed_near_mouth: 0.06
          max_linear_speed: 0.15
          plan_distance_from_mouth:
          - 0.025
          - 0.0
          - -0.01
        tree_kws:
        - face_detection_msg_timeout
        - face_detection_timeout
        - fork_target_orientation_from_mouth
        - plan_distance_from_mouth
        - max_linear_speed
        - linear_speed_near_mouth
      MoveToRestingPosition:
        action_type: ada_feeding_msgs.action.MoveTo
        tick_rate: 10
        tree_class: ada_feeding.trees.MoveToConfigurationWithWheelchairWallTree
        tree_kwargs:
          allowed_planning_time: 1.0
          goal_configuration:
          - -1.94672
          - 2.51268
          - 0.35653
          - -4.76501
          - 5.99991
          - 4.99555
          joint_positions:
          - 3.7584342379702265
          - -3.0680026297628116
          - 0.11208646011532394
          - 0.00303070749096387
          - -0.05027405112606054
          - -1.7464533479809023
          - -2.085948872615267
          max_velocity_scaling_factor: 1.0
          orientation_constraint_quaternion:
          - 0.707168
          - 0.0
          - 0.0
          - 0.707168
          orientation_constraint_tolerances:
          - 0.6
          - 3.14159
          - 0.5
        tree_kws:
        - goal_configuration
        - allowed_planning_time
        - max_velocity_scaling_factor
      MoveToStagingConfiguration:
        action_type: ada_feeding_msgs.action.MoveTo
        tick_rate: 10
        tree_class: ada_feeding.trees.MoveToConfigurationWithWheelchairWallTree
        tree_kwargs:
          allowed_planning_time: 1.0
          goal_configuration:
          - -2.32526
          - 4.456298
          - 4.16769
          - 1.53262
          - -2.18359
          - -2.19525
          joint_positions:
          - -0.34364307728668453
          - -2.621612844118122
          - -0.019451526899020067
          - -0.0007478863155584548
          - -2.961872137853919
          - 2.256032732630817
          - -1.0554859623695632
          max_velocity_scaling_factor: 1.0
          orientation_constraint_quaternion:
          - 0.707168
          - 0.0
          - 0.0
          - 0.707168
          orientation_constraint_tolerances:
          - 0.6
          - 3.14159
          - 0.5
        tree_kws:
        - goal_configuration
        - allowed_planning_time
        - max_velocity_scaling_factor
      MoveToStowLocation:
        action_type: ada_feeding_msgs.action.MoveTo
        tick_rate: 10
        tree_class: ada_feeding.trees.MoveToConfigurationWithFTThresholdsTree
        tree_kwargs:
          f_mag: 4.0
          joint_positions:
          - -1.8097409330951433
          - -3.034236319518189
          - -0.5886060906556563
          - -0.01662584917147908
          - -2.3607675332619724
          - 1.924388137639693
          - 0.4534271435389849
          max_velocity_scaling_factor: 1.0
          toggle_watchdog_listener: false
        tree_kws:
        - joint_positions
        - toggle_watchdog_listener
        - f_mag
        - max_velocity_scaling_factor
      StartServo:
        action_type: ada_feeding_msgs.action.Trigger
        tick_rate: 10
        tree_class: ada_feeding.trees.StartServoTree
      StopServo:
        action_type: ada_feeding_msgs.action.Trigger
        tick_rate: 10
        tree_class: ada_feeding.trees.StopServoTree
      TestMoveToPose:
        action_type: ada_feeding_msgs.action.MoveTo
        tick_rate: 10
        tree_class: ada_feeding.trees.MoveToPoseTree
        tree_kwargs:
          max_velocity_scaling_factor: 1.0
          position:
          - 0.28323
          - 0.07289
          - 0.69509
          quat_xyzw:
          - 0.00472
          - 0.69757
          - 0.71645
          - -0.00811
        tree_kws:
        - position
        - quat_xyzw
        - max_velocity_scaling_factor
      planning_scene_namespace_to_use: seated
      server_names:
      - MoveAbovePlate
      - AcquireFood
      - MoveToRestingPosition
      - MoveToStagingConfiguration
      - MoveToMouth
      - MoveFromMouth
      - MoveToStowLocation
      - TestMoveToPose
      - StartServo
      - StopServo
      - ActivateController
      - MoveToConfiguration
    watchdog_timeout_sec: 0.5
